name: "Release tag"
env:
  DOCKERHUB_REPOSITORY: serjs/go-socks5-proxy

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, edited]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.1.0
      - name: Release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Print release version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Dockerhub login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --push \
            --tag "$DOCKERHUB_REPOSITORY:$RELEASE_VERSION" \
            .
